/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;  // this is for popup messages like errors etc.. 


public class CollageSystem extends javax.swing.JFrame {


    public CollageSystem() {
        initComponents();
        EmpP.setVisible(false);
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainGroup = new javax.swing.ButtonGroup();
        MainGroup2 = new javax.swing.ButtonGroup();
        TAgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nxtf1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jrStudent = new javax.swing.JRadioButton();
        jrEmp = new javax.swing.JRadioButton();
        EmpP = new javax.swing.JPanel();
        Rprofessor = new javax.swing.JRadioButton();
        RTA = new javax.swing.JRadioButton();
        RNleaner = new javax.swing.JRadioButton();
        RWorker = new javax.swing.JRadioButton();
        RManger = new javax.swing.JRadioButton();
        RSecurity = new javax.swing.JRadioButton();
        RIt = new javax.swing.JRadioButton();
        RClinicDr = new javax.swing.JRadioButton();
        RClinicAssist = new javax.swing.JRadioButton();
        RCafe = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Collage Managment System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Please Select Your Correct Role");

        Nxtf1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nxtf1.setText("NEXT");
        Nxtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nxtf1ActionPerformed(evt);
            }
        });

        MainGroup.add(jrStudent);
        jrStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrStudent.setText("Student");
        jrStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrStudentActionPerformed(evt);
            }
        });

        MainGroup.add(jrEmp);
        jrEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrEmp.setText("Employee");
        jrEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrEmp)
                    .addComponent(jrStudent))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jrStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrEmp)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        EmpP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                EmpPComponentHidden(evt);
            }
        });

        MainGroup2.add(Rprofessor);
        Rprofessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rprofessor.setText("Professor");
        Rprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RprofessorActionPerformed(evt);
            }
        });

        MainGroup2.add(RTA);
        RTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RTA.setText("TA");
        RTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTAActionPerformed(evt);
            }
        });

        MainGroup2.add(RNleaner);
        RNleaner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RNleaner.setText("Cleaner");

        MainGroup2.add(RWorker);
        RWorker.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RWorker.setText("Worker");

        MainGroup2.add(RManger);
        RManger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RManger.setText("Manager");

        MainGroup2.add(RSecurity);
        RSecurity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RSecurity.setText("Security");
        RSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSecurityActionPerformed(evt);
            }
        });

        MainGroup2.add(RIt);
        RIt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RIt.setText("IT");

        MainGroup2.add(RClinicDr);
        RClinicDr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RClinicDr.setText("Clinic Doctor");

        MainGroup2.add(RClinicAssist);
        RClinicAssist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RClinicAssist.setText("Clinic Assistant");

        MainGroup2.add(RCafe);
        RCafe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RCafe.setText("Cafe Employee");

        javax.swing.GroupLayout EmpPLayout = new javax.swing.GroupLayout(EmpP);
        EmpP.setLayout(EmpPLayout);
        EmpPLayout.setHorizontalGroup(
            EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RWorker)
                    .addGroup(EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Rprofessor)
                        .addComponent(RTA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RNleaner, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RManger, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(146, 146, 146)
                .addGroup(EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RSecurity)
                    .addComponent(RClinicDr)
                    .addComponent(RClinicAssist)
                    .addGroup(EmpPLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RIt)
                            .addComponent(RCafe))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        EmpPLayout.setVerticalGroup(
            EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(EmpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpPLayout.createSequentialGroup()
                        .addComponent(RSecurity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RClinicDr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RClinicAssist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RCafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RIt))
                    .addGroup(EmpPLayout.createSequentialGroup()
                        .addComponent(Rprofessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RNleaner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RWorker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RManger)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Nxtf1)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nxtf1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEmpActionPerformed
        // TODO add your handling code here:
        EmpP.setVisible(true);
    }//GEN-LAST:event_jrEmpActionPerformed

    private void jrStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrStudentActionPerformed
        // TODO add your handling code here:
        EmpP.setVisible(false);
    }//GEN-LAST:event_jrStudentActionPerformed

    private void Nxtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nxtf1ActionPerformed
        // Next Button In Form 1 , login form
        if (jrEmp.isSelected() ){
       if (RTA.isSelected()) {
          new TA().setVisible(true);
          this.setVisible(false);       
          
        }

        
        } 
        else  if (jrStudent.isSelected() ){
         new Student().setVisible(true);
        this.setVisible(false);
        
        }else {
               JOptionPane.showMessageDialog(null, "Please Select a Role !! ","Error!", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_Nxtf1ActionPerformed

    private void RprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RprofessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RprofessorActionPerformed

    private void RSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSecurityActionPerformed

    private void EmpPComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_EmpPComponentHidden
        // TODO add your handling code here:
   
    }//GEN-LAST:event_EmpPComponentHidden

    private void RTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTAActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RTAActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollageSystem().setVisible(true);
            }
        });
    }
   

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmpP;
    private javax.swing.ButtonGroup MainGroup;
    private javax.swing.ButtonGroup MainGroup2;
    private javax.swing.JButton Nxtf1;
    private javax.swing.JRadioButton RCafe;
    private javax.swing.JRadioButton RClinicAssist;
    private javax.swing.JRadioButton RClinicDr;
    private javax.swing.JRadioButton RIt;
    private javax.swing.JRadioButton RManger;
    private javax.swing.JRadioButton RNleaner;
    private javax.swing.JRadioButton RSecurity;
    private javax.swing.JRadioButton RTA;
    private javax.swing.JRadioButton RWorker;
    private javax.swing.JRadioButton Rprofessor;
    private javax.swing.ButtonGroup TAgroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrEmp;
    private javax.swing.JRadioButton jrStudent;
    // End of variables declaration//GEN-END:variables
}
